Add new join benchmarks
WGierke/tuk1_numa_a pull request #13
Opened 2017-06-28 20:32 UTC by lawben

This PR is to discuss possible join benchmarks to be added. We currently have both tables Local, both remote but on different nodes and one local, one remote.

2017-06-28 21:44 UTC, WGierke commented
```
    {
      "name": "BM_Join__DifferentRemoteTables/1000000",
      "iterations": 1,
      "real_time": 797639,
      "cpu_time": 797613,
      "time_unit": "us"
    }mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
mbind: Invalid argument
,
    {
      "name": "BM_Join__DifferentRemoteTables/2000000",
      "iterations": 1,
      "real_time": 1189592,
      "cpu_time": 1189551,
      "time_unit": "us"
    },
    {
      "name": "BM_ColumnScan_1M_Rows__LocalCols/1",
      "iterations": 5852,
      "real_time": 121,
      "cpu_time": 121,
      "time_unit": "us"
    },
    {
      "name": "BM_ColumnScan_1M_Rows__LocalCols/2",
      "iterations": 2295,
      "real_time": 310,
      "cpu_time": 310,
      "time_unit": "us"
    },
    {
      "name": "BM_ColumnScan_1M_Rows__LocalCols/4",
      "iterations": 966,
      "real_time": 725,
      "cpu_time": 725,
      "time_unit": "us"
    },
    {
      "name": "BM_ColumnScan_1M_Rows__LocalCols/8",
      "iterations": 460,
      "real_time": 1642,
      "cpu_time": 1642,
      "time_unit": "us"
    }[1]    3526 floating point exception (core dumped)  ./src/tuk_numa_benchmark --benchmark_format=json
```

2017-06-28 21:52 UTC, StarkRobert requested changes

2017-06-28 21:52 UTC, StarkRobert commented on src/main.cpp
> +        {2000, 2000000},
this gives us
2k, 10k, 100k, 1M, 2M

instead of
2k, 20k, 200k, 2M

2017-06-29 09:34 UTC, rs22 commented
The benchmark framework determined the range entries by taking all multiples of the provided multiplier that are between the lower and upper range bounds, plus the bounds itself.

I think their reasoning was "we're benchmarking different orders of magnitudes, so another multiplicative constant doesn't matter".

I've adjusted the framework code to make it work for us.

2017-06-29 09:34 UTC, rs22 approved these changes

2017-06-29 09:36 UTC, StarkRobert approved these changes

2017-06-29 09:36 UTC, merged